export const MEDICINE_LIST_REQUEST = 'MEDICINE_LIST_REQUEST'
export const MEDICINE_LIST_SUCCESS = 'MEDICINE_LIST_SUCCESS'
export const MEDICINE_LIST_FAIL = 'MEDICINE_LIST_FAIL'


export const MEDICINE_DETAILS_REQUEST = 'MEDICINE_DETAILS_REQUEST'
export const MEDICINE_DETAILS_SUCCESS = 'MEDICINE_DETAILS_SUCCESS'
export const MEDICINE_DETAILS_FAIL = 'MEDICINE_DETAILS_FAIL'


export const MEDICINE_DELETE_REQUEST = 'MEDICINE_DELETE_REQUEST'
export const MEDICINE_DELETE_SUCCESS = 'MEDICINE_DELETE_SUCCESS'
export const MEDICINE_DELETE_FAIL = 'MEDICINE_DELETE_FAIL'

export const MEDICINE_CREATE_REQUEST = 'MEDICINE_CREATE_REQUEST'
export const MEDICINE_CREATE_SUCCESS = 'MEDICINE_CREATE_SUCCESS'
export const MEDICINE_CREATE_FAIL = 'MEDICINE_CREATE_FAIL'
export const MEDICINE_CREATE_RESET = 'MEDICINE_CREATE_RESET'

export const MEDICINE_UPDATE_REQUEST = 'MEDICINE_UPDATE_REQUEST'
export const MEDICINE_UPDATE_SUCCESS = 'MEDICINE_UPDATE_SUCCESS'
export const MEDICINE_UPDATE_FAIL = 'MEDICINE_UPDATE_FAIL'
export const MEDICINE_UPDATE_RESET = 'MEDICINE_UPDATE_RESET'

export const MEDICINE_CREATE_REVIEW_REQUEST = 'MEDICINE_CREATE_REVIEW_REQUEST'
export const MEDICINE_CREATE_REVIEW_SUCCESS = 'MEDICINE_CREATE_REVIEW_SUCCESS'
export const MEDICINE_CREATE_REVIEW_FAIL = 'MEDICINE_CREATE_REVIEW_FAIL'
export const MEDICINE_CREATE_REVIEW_RESET = 'MEDICINE_CREATE_REVIEW_RESET'