export const SHIPPER_LIST_REQUEST = "SHIPPER_LIST_REQUEST";
export const SHIPPER_LIST_SUCCESS = "SHIPPER_LIST_SUCCESS";
export const SHIPPER_LIST_FAIL = "SHIPPER_LIST_FAIL";

export const SHIPPER_DETAILS_REQUEST = "SHIPPER_DETAILS_REQUEST";
export const SHIPPER_DETAILS_SUCCESS = "SHIPPER_DETAILS_SUCCESS";
export const SHIPPER_DETAILS_FAIL = "SHIPPER_DETAILS_FAIL";

export const SHIPPER_DELETE_REQUEST = "SHIPPER_DELETE_REQUEST";
export const SHIPPER_DELETE_SUCCESS = "SHIPPER_DELETE_SUCCESS";
export const SHIPPER_DELETE_FAIL = "SHIPPER_DELETE_FAIL";

export const SHIPPER_CREATE_REQUEST = "SHIPPER_CREATE_REQUEST";
export const SHIPPER_CREATE_SUCCESS = "SHIPPER_CREATE_SUCCESS";
export const SHIPPER_CREATE_FAIL = "SHIPPER_CREATE_FAIL";
export const SHIPPER_CREATE_RESET = "SHIPPER_CREATE_RESET";

export const SHIPPER_UPDATE_REQUEST = "SHIPPER_UPDATE_REQUEST";
export const SHIPPER_UPDATE_SUCCESS = "SHIPPER_UPDATE_SUCCESS";
export const SHIPPER_UPDATE_FAIL = "SHIPPER_UPDATE_FAIL";
export const SHIPPER_UPDATE_RESET = "SHIPPER_UPDATE_RESET";

export const SHIPPER_CREATE_REVIEW_REQUEST = "SHIPPER_CREATE_REVIEW_REQUEST";
export const SHIPPER_CREATE_REVIEW_SUCCESS = "SHIPPER_CREATE_REVIEW_SUCCESS";
export const SHIPPER_CREATE_REVIEW_FAIL = "SHIPPER_CREATE_REVIEW_FAIL";
export const SHIPPER_CREATE_REVIEW_RESET = "SHIPPER_CREATE_REVIEW_RESET";
export const SHIPPER_LOGIN_SUCCESS = "SHIPPER_LOGIN_SUCCESS";
export const SHIPPER_LOGIN_FAIL = "SHIPPER_LOGIN_FAIL";
export const SHIPPER_LOGOUT = "SHIPPER_LOGOUT";
export const SHIPPER_DETAILS_RESET = "SHIPPER_DETAILS_RESET";
export const SHIPPER_LOGIN_REQUEST = "SHIPPER_LOGIN_REQUEST";
export const SHIPPER_UPDATE_PROFILE_REQUEST = "SHIPPER_UPDATE_PROFILE_REQUEST";

export const SHIPPER_UPDATE_PROFILE_FAIL = "SHIPPER_UPDATE_PROFILE_FAIL";
export const SHIPPER_LIST_RESET = "SHIPPER_LIST_RESET";
export const SHIPPER_UPDATE_PROFILE_SUCCESS = "SHIPPER_UPDATE_PROFILE_SUCCESS";
