//export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
//export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";



// export const GET_ALL_PHARMACIES_SUCCESS = "GET_ALL_PHARMACIES_SUCCESS";
// export const GET_ALL_PHARMACIES_FAIL = "GET_ALL_PHARMACIES_FAIL";

export const EMAIL_CONFIRMED_SUCCESS = "EMAIL_CONFIRMED_SUCCESS";
export const EMAIL_CONFIRMED_FAIL = "EMAIL_CONFIRMED_FAIL";
export const GET_EMAIL_CONFIRMED_SUCCESS = "GET_EMAIL_CONFIRMED_SUCCESS";
export const GET_EMAIL_CONFIRMED_FAIL = "GET_EMAIL_CONFIRMED_FAIL";
//Update passowrd types_
export const UPDATE_P_PASSWORD_SUCCESS = "UPDATE_P_PASSWORD_SUCCESS";
export const UPDATE_P_PASSWORD_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_P_PICTURE_SUCCESS = "UPDATE_P_PICTURE_SUCCESS";
export const UPDATE_P_PICTURE_FAIL = "UPDATE_PROFILE_FAIL";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAIL = "GET_ROLES_FAIL";

export const FETCH_USERS = "FETCH_USERS";





export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
